name: Isort Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  isort-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      
    - name: Install dependencies
      run: uv sync
    
    - name: Run Isort Check
      id: isort-check
      run: uv run isort . --check --diff --verbose
      continue-on-error: true

    - name: Check Isort Results
      uses: actions/github-script@v7
      with:
        script: |
          const stepOutcome = '${{ steps.isort-check.outcome }}';
          const isSuccess = stepOutcome === 'success';
          
          if (isSuccess) {
            console.log("✅ Isort check passed");
            console.log("All Python imports are properly sorted");
          } else {
            console.error("❌ Isort check failed");
            console.error("Python imports need to be sorted");
            console.error("Run 'uv run isort .' to fix the formatting");
            core.setFailed("Isort check failed - imports need to be sorted");
          }