name: Run PDF Reader

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  workflow_dispatch: 

jobs:
  read-pdf-fields:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: latest
        
    - name: Install dependencies
      run: uv sync
      
    - name: List project structure
      run: |
        echo "Project structure:"
        find . -type f -name "*.py" -o -name "*.pdf" | head -20
        
    - name: Check PDF file exists
      run: |
        if [ -f "docs/Sample-Fillable-PDF.pdf" ]; then
          echo "✅ PDF file found"
          ls -la docs/
        else
          echo "❌ PDF file not found"
          exit 1
        fi
        
    - name: Run PDF Reader
      id: pdf-reader
      run: |
        echo "Reading PDF form fields..."
        uv run src/read_fields.py
        echo "exit_code=$?" >> $GITHUB_OUTPUT
        
    - name: Check script exit code
      if: steps.pdf-reader.outputs.exit_code != '0'
      run: |
        echo "❌ PDF reader script failed with exit code ${{ steps.pdf-reader.outputs.exit_code }}"
        exit 1
        
    - name: Success message
      if: steps.pdf-reader.outputs.exit_code == '0'
      run: |
        echo "✅ PDF reader completed successfully!"